title: Poorani Aravindan # your name (or website title) here
logo: "/images/pooran-cartooni.png" # your photo (or logo) 
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>
  Technical Writing | Information Architecture | Content Strategy | Content Management
  <br><br>
    <br>
  <a href="https://pooraniarvind.github.io/index"><b>About me</b></a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/pooraniaravindan/"><font size="-2"><b>LinkedIn</b></font></a> <a href="https://drive.google.com/file/d/1fjx1G70dfBGa7SzfNsoP76zbzt4TLxUj/view?usp=sharing"><b> | Resume</b></a> <a href="https://github.com/pooraniarvind/pooraniarvind.github.io"><b> | GitHub </b> </font></a>
  <br> <br>
theme: jekyll-theme-minimal
google_analytics: UA-142866422-1 # your Google Analytics tracking ID here
